## Test configuration name. Used for reporting.
name: Network and HTTP screwer.

## Test Description. Used for reporting
description: Slow network to mobile levels, and add 1s delay to all messages

## Specify log output level
##
## Log Levels supported:
## Trace (0), Debug (1), Info (2, Default), Warn (3), Error (4), Fatal (5)
loglevel: 4

## Configure a proxy that will handle your requests, and forward
## to proxied host.
##
## Currently supports `tcp_proxy` and `http_proxy`.
proxy:

  ## HTTP Proxy: Configures an HTTP Proxy
  ##
  ## NOTE: SSL is currently not supported
  - name: http_proxy
    config:
      host: 0.0.0.0
      port: 80
      protocol: http
      proxy_host: backend
      proxy_port: 80
      proxy_protocol: http

## Middleware
##
## Middleware are plugins that are given the opportunity to intervene
## before a request is dispatched to the proxied system (PRE_DISPATCH event)
## and afterwards (POST_DISPATCH event). They are given a reference to
## the current context (HTTP Context or []bytes) and can mutate them.
##
## Middleware are executed in the order specified in this config.
##
middleware:

  ## Request Logger - use this to see what's going in/out of the Proxy.
  ##
  ##
  - name: logger
    config:
      hex_output: false        # Display output as Hex instead of a string

  ## Network Shaper - Layer 4 Tamperer.
  ##
  ## Uses Comcast (github.com/tylertreat/comcast) to shape and interfere with network traffic,
  ## including bandwidth, latency, packet loss and jitter on specified ports, IPs and protocols.
  ##
  ## NOTE: This plugin requires root/sudo access to run
  #
  - name: network_shape
    config:
      latency:     10         # Latency to add in ms
      target_bw:   750        # Bandwidth in kbits/s
      default_bw:  750
      packet_loss: 0          # Packet loss, as a %
      target_ports:
        - "80"
      target_protos:          # Target protocols
        - "tcp"
        - "udp"
        - "icmp"
      target_ips:
      - "0.0.0.0/0"
      device: "eth0"

  # Enable this to fail the lot!
  # - name: http_tamperer
  #   config:
  #     response:
  #       status: 500              # Override HTTP Status code
